jupyterhub:
  singleuser:
    image:
      name: us.gcr.io/pangeo-181919/example-pangeo-io-notebook
    cloudMetadata:
      enabled: true
    cpu:
      limit: 4
      guarantee: 1
    memory:
      limit: 14G
      guarantee: 4G
